config/routes.rb
Rails.application.routes.draw do

  # Session 
  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

  resources :sessions, only: [:new, :create]

  root to: 'gossips#index'

  get '/profile', to: 'users#edit', as: :profile
  patch '/profile', to: 'users#update'
  
  resources :users, only:  [:new, :create, :show, :edit, :update] do 
    member do 
      get 'confirm'
    end
  end

  resources :cities
  resources :users
  resources :gossips

  get '/welcome/:first_name', to: 'welcome#get_username'
  get '/contact', to: 'contact#info'
  get '/team', to: 'team#presentation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :zip_code,
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
    
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { in: 3..30 }
  validates :content,
    presence: true

  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, 
  uniqueness: {case_sensitive: false}

  validates :first_name,
    presence: true,
    length: { minimum: 2 }

  validates :last_name,
    presence: true,
    length: { minimum: 2 }

  validates :email,
    presence: true,
    # format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please " },
    uniqueness: {case_sensitive: false}
  
  has_secure_password
  validates :password, 
    presence: true, 
    length: { minimum: 5 }
  
  has_secure_token :confirmation_token
    
  belongs_to :city, optional: true
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  def to_session
    {id: id}
  end 
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    id = params[:id].to_i  
    @city = City.find_by(id: id)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def info
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def new
  end

  def show  
    id = params[:id].to_i  
    @gossip = Gossip.find_by id: id  
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content)
    if @gossip.update(gossip_params)
    redirect_to gossips_path
    else
      render :edit
    end
  end

  def create
    @gossip = Gossip.new(title: params[:title],
    content: params[:content],
    user: User.find(session[:auth]['id']))
    # User.find(params[:user])
    if @gossip.save
    redirect_to root_path
    else 
      render 'new'
    end
    
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  def index 
  end

private


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create]
  before_action :only_signed_out, only: [:new, :create]

  def new
  end

  def create
    user_params = params.require(:user)
    @user = User.where(username: user_params[:username]).or(User.where(email: user_params[:username])).first
    if @user and @user.authenticate(user_params[:password])
      session[:auth] = @user.to_session
      redirect_to root_path, success: "You are now connected! "
    else 
      redirect_to new_session_path, danger: "Inccorrect authentification"
    end
  end

  def destroy
    session.destroy
    redirect_to login_path, success: 'You are now log out'
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def presentation
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create, :confirm]
  before_action :only_signed_out, only: [:new, :create, :confirm]

  def show
    id = params[:id].to_i  
    @user = User.find_by id: id 
  end

  def new
    @user = User.new
  end

  def create    
    user_params = params.require(:user).permit(:username, :first_name, :last_name, :email, :city_id, :password, :password_confirmation)
     @user = User.new(user_params)
     @user.city = City.all.find_by(id: params[:city])
   
     if @user.valid?
      @user.save
      redirect_to new_session_path, success: 'Your account has been created with success! 🎉'
     else 
      render 'new'
     end
  end

  def confirm 
    @user = User.find(params[:id])
    if @user.confirmation_token == params[:token]
      @user.update_attributes(confirmed: true, confirmation_token: nil)
      @user.save(validate: false )
      session[:auth] = @user.to_session
      redirect_to profile_path, success: 'Your account has been confirmed! 🤩'
    else 
      redirect_to new_user_path, danger: 'This token is not valid'
    end
  end

  def edit
    # @user = User.find(session[:auth]['id'])
    @user = current_user
  end

  def update
  end

  def destroy
  end

  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def get_username
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/create.html.erb
<h1>Gossips#create</h1>
<p>Find me in app/views/gossips/create.html.erb</p>

app/views/gossips/destroy.html.erb
<h1>Gossips#destroy</h1>
<p>Find me in app/views/gossips/destroy.html.erb</p>

app/views/gossips/edit.html.erb
<div class="ml-5 mr-5">
  <h3 class="mb-4 mt-4">Edit gossip</h3>
  <%= form_for @gossip do |f| %>
    <div class="form-group">
      <label>Gossip title</label>
      <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class="form-group">
    <label>Gossip content</label>
      <%= f.text_area :content, class: 'form-control'%>
    </div>
    <div class="form-group">
    <button type="subimit" class="btn btn-outline-info">Edit gossip</button>
    </div>
  <% end %>
</div>

app/views/gossips/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4 m-2 ml-4 mt-4 text-center">Welcome to The Gossip Project!</h1>
    <p class="lead m-2 ml-4 mb-5 text-center"></p>
  </div>
</div>

<div class="card-deck">
  <% Gossip.all.each do |gossip| %>
    <div class="col-lg-3 col-md-6 mb-3">
      <div class="card text-center my-3">
        <div class="card-body">
          <h5 class="card-title ">Gossip n° <%= gossip.id %></h5>
          <h5 class="card-title text-secondary"> Title : <%= gossip.title%></h5>
          <p class="card-text"> Author: <%= gossip.user.first_name %> </p>
          <a href="<%= gossip_path(gossip.id) %>" class="btn btn-info text-center">View gossip</a><br><br>
          
        </div>

        <div class="card-footer">
          <p class="small text-muted mr-0">
            Post by <%= link_to "#{gossip.user.first_name} #{gossip.user.last_name}", user_path(gossip.user.id) %> on <%= gossip.created_at.strftime("%d/%m/%Y") %> at <%= gossip.created_at.strftime("%H:%I") %>.
            <%# Located: <%= link_to "#{gossip.user.city.name}", city_path(gossip.user.city.id) %> 
          </p>
        </div>

      </div>
    </div>
  <% end %>
</div>

app/views/gossips/new.html.erb
<h1 class="text-center m-3 mt-5">Add a new gossip</h1>


<div class="row justify-content-center">
  <div class="col-5">
    <%= form_tag url_for(action: 'create'), method: "post" do %>
      <div class="form-group">
        <%= label_tag 'Title :' %>
        <%= text_field_tag 'title', @title, {class: 'form-control'} %>
      </div>
      <div class="form-group">
        <%= label_tag 'Content :' %>
        <%= text_area_tag 'content', @content, {class: 'form-control'} %>
      </div>

      <%# <div class="form-group">
      <%= label_tag 'Author :' %>
      <%# <%= text_area_tag 'user', @user, {class: 'form-control'} %> 
      <%# </div>  %>
      <%# <div class="form-group">
        <%= label_tag 'Author :' %>
        <%# <%= select_tag "user", options_from_collection_for_select(User.all, :id, :first_name), {class: 'form-control', prompt: 'Choose a user'} %>
      <%# </div>  %>
      
      <div class="row justify-content-center">
          <%= submit_tag "Create gossip", {class: 'btn btn-info'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/gossips/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gossip details</title>
</head>
<body>

  <div class="card">
    <div class="card-header">
      <p> Title: <%= @gossip.title %> </p>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <h4>Content:</h4>
        <p> <%=@gossip.content %> </p>
        <footer class="blockquote-footer">Post by <%= link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", user_path(@gossip.user.id) %> Located : <%=@gossip.user.city.name %> on <%= @gossip.created_at.strftime("%d/%m/%Y") %> at <%= @gossip.created_at.strftime("%H:%I") %> </cite></footer>
      </blockquote>
    </div>
  </div>
  
  <a href="<%= edit_gossip_path(@gossip.id) %>" class="btn btn-outline-secondary text-center ml-3 mt-2">Edit gossip</a>
  <a href="<%= gossip_path(@gossip.id) %>" class="btn btn-danger text-center ml-3 mt-2" data-confirm="are you sure?" data-method="DELETE">Delete gossip</a>

</body>
</html>
  
   

app/views/gossips/update.html.erb
<h1>Gossips#update</h1>
<p>Find me in app/views/gossips/update.html.erb</p>