config/routes.rb
Rails.application.routes.draw do

  # Session 
  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session

  resources :sessions, only: [:new, :create]

  root to: 'gossips#index'

  get '/profile', to: 'users#edit', as: :profile
  patch '/profile', to: 'users#update'
  
  resources :users, only:  [:new, :create, :show, :edit, :update] do 
    member do 
      get 'confirm'
    end
  end

  resources :cities
  resources :users
  resources :gossips

  get '/welcome/:first_name', to: 'welcome#get_username'
  get '/contact', to: 'contact#info'
  get '/team', to: 'team#presentation'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  validates :zip_code,
    format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
    
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { in: 3..30 }
  validates :content,
    presence: true

  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, 
  uniqueness: {case_sensitive: false}

  validates :first_name,
    presence: true,
    length: { minimum: 2 }

  validates :last_name,
    presence: true,
    length: { minimum: 2 }

  validates :email,
    presence: true,
    # format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please " },
    uniqueness: {case_sensitive: false}
  
  has_secure_password
  validates :password, 
    presence: true, 
    length: { minimum: 5 }
  
  has_secure_token :confirmation_token
    
  belongs_to :city, optional: true
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

  def to_session
    {id: id}
  end 
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    id = params[:id].to_i  
    @city = City.find_by(id: id)
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def presentation
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :only_signed_in, only: [:new, :create, :confirm]
  before_action :only_signed_out, only: [:new, :create, :confirm]

  def show
    id = params[:id].to_i  
    @user = User.find_by id: id 
  end

  def new
    @user = User.new
  end

  def create    
    user_params = params.require(:user).permit(:username, :first_name, :last_name, :email, :city_id, :password, :password_confirmation)
     @user = User.new(user_params)
     @user.city = City.all.find_by(id: params[:city])
   
     if @user.valid?
      @user.save
      redirect_to new_session_path, success: 'Your account has been created with success! 🎉'
     else 
      render 'new'
     end
  end

  def confirm 
    @user = User.find(params[:id])
    if @user.confirmation_token == params[:token]
      @user.update_attributes(confirmed: true, confirmation_token: nil)
      @user.save(validate: false )
      session[:auth] = @user.to_session
      redirect_to profile_path, success: 'Your account has been confirmed! 🤩'
    else 
      redirect_to new_user_path, danger: 'This token is not valid'
    end
  end

  def edit
    # @user = User.find(session[:auth]['id'])
    @user = current_user
  end

  def update
  end

  def destroy
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
  </head>

  <body> 

      <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
      
      <% if user_signed_in? %>

        <a class="navbar-brand" href="<%= root_path %>">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= new_gossip_path %>">Add a gossip</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link" href="<%= team_path %>">Team<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=" <%= contact_path %> ">Contact</a>
          </li>
           <li class="nav-item">
            <a class="nav-link" href="<%= profile_path %>"><%= current_user.username %>'s Profile</a>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_session_path, data: {method: :delete, :confirm => 'Do you really want to leave? 😢'}, :class =>"nav-link"%>
          </li>
        </ul>

          <% else %>
          <ul class="navbar-nav">
            <li class="nav-item ">
              <a class="nav-link " href="<%= new_user_path %>">Sign up</a>
            </li>
             <li class="nav-item">
              <a class="nav-link" href="<%= new_session_path %>">Connexion</a>
            </li>
          </ul>
          <% end %>
          <!--
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          -->
        </ul>
      </div>
    </nav>

  <div class="">

    <% if flash[:success] %>
    <div class="alert alert-success">
      <%= flash[:success] %>
    </div>
    <% end %>

    <% if flash[:danger] %>
    <div class="alert alert-danger">
      <%= flash[:danger] %>
    </div>
    <% end %>

    <%= yield %>
  </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Require JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    
  </body>
</html>